"""add_missing_chunk_columns

Revision ID: 389233fed320
Revises: e2ccf094dbbe
Create Date: 2026-03-07 01:42:44.289365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '389233fed320'
down_revision: Union[str, None] = 'e2ccf094dbbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('page_number', sa.Integer(), nullable=True))
    op.add_column('document_chunks', sa.Column('metadata', sa.JSON(), nullable=True))
    op.add_column('document_chunks', sa.Column('search_vector', postgresql.TSVECTOR(), nullable=True))
    op.drop_constraint('document_chunks_document_id_fkey', 'document_chunks', type_='foreignkey')
    op.create_foreign_key(None, 'document_chunks', 'documents', ['document_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'document_chunks', type_='foreignkey')
    op.create_foreign_key('document_chunks_document_id_fkey', 'document_chunks', 'documents', ['document_id'], ['id'])
    op.drop_column('document_chunks', 'search_vector')
    op.drop_column('document_chunks', 'metadata')
    op.drop_column('document_chunks', 'page_number')
    # ### end Alembic commands ###
