"""add embedding columns

Revision ID: 602740e83141
Revises: 0aa1f2b3c4d5
Create Date: 2026-04-25 22:24:42.413821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = '602740e83141'
down_revision: Union[str, None] = '0aa1f2b3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('embedding_gemini', pgvector.sqlalchemy.Vector(dim=768), nullable=True))
    op.add_column('document_chunks', sa.Column('embedding_provider', sa.String(), nullable=True))
    op.drop_index('ix_dc_embedding_hnsw', table_name='document_chunks', postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_index('ix_dc_user_project', table_name='document_chunks')
    op.create_index(op.f('ix_document_chunks_project_id'), 'document_chunks', ['project_id'], unique=False)
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.create_index(op.f('ix_feedback_created_at'), 'feedback', ['created_at'], unique=False)
    op.add_column('projects', sa.Column('embedding_provider', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('retrieval_strategy', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('allow_errors', sa.Boolean(), nullable=True))
    op.add_column('projects', sa.Column('enable_web_search', sa.Boolean(), nullable=True))
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usage_logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.create_index(op.f('ix_usage_logs_created_at'), 'usage_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_usage_logs_project_id'), 'usage_logs', ['project_id'], unique=False)
    op.create_index(op.f('ix_usage_logs_user_id'), 'usage_logs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_usage_logs_user_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_project_id'), table_name='usage_logs')
    op.drop_index(op.f('ix_usage_logs_created_at'), table_name='usage_logs')
    op.alter_column('usage_logs', 'latency_ms',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_logs', 'tokens_used',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('usage_logs', 'project_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('usage_logs', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('projects', 'enable_web_search')
    op.drop_column('projects', 'allow_errors')
    op.drop_column('projects', 'retrieval_strategy')
    op.drop_column('projects', 'embedding_provider')
    op.drop_index(op.f('ix_feedback_created_at'), table_name='feedback')
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_project_id'), table_name='document_chunks')
    op.create_index('ix_dc_user_project', 'document_chunks', ['user_id', 'project_id'], unique=False)
    op.create_index('ix_dc_embedding_hnsw', 'document_chunks', ['embedding'], unique=False, postgresql_with={'m': '16', 'ef_construction': '64'}, postgresql_using='hnsw')
    op.drop_column('document_chunks', 'embedding_provider')
    op.drop_column('document_chunks', 'embedding_gemini')
    # ### end Alembic commands ###
