"""hash_api_keys

Revision ID: 9b36bf1b9ce3
Revises: 60f62404aa55
Create Date: 2026-03-07 02:44:08.282077

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '9b36bf1b9ce3'
down_revision: Union[str, None] = '60f62404aa55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Delete existing plaintext keys before we add non-nullable hash columns
    op.execute("DELETE FROM api_keys")
    op.add_column('api_keys', sa.Column('key_hash', sa.String(), nullable=False))
    op.add_column('api_keys', sa.Column('prefix', sa.String(), nullable=False))
    op.drop_index('ix_api_keys_key', table_name='api_keys')
    op.create_index(op.f('ix_api_keys_key_hash'), 'api_keys', ['key_hash'], unique=True)
    op.drop_column('api_keys', 'key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('key', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_api_keys_key_hash'), table_name='api_keys')
    op.create_index('ix_api_keys_key', 'api_keys', ['key'], unique=True)
    op.drop_column('api_keys', 'prefix')
    op.drop_column('api_keys', 'key_hash')
    # ### end Alembic commands ###
