"""Add role column to users

Revision ID: e2ccf094dbbe
Revises: 5d27e3e22a4f
Create Date: 2026-02-17 15:05:54.008752

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector


# revision identifiers, used by Alembic.
revision: str = 'e2ccf094dbbe'
down_revision: Union[str, None] = '5d27e3e22a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('projects', sa.Column('llm_model', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('embedding_model', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('temperature', sa.Float(), nullable=True))
    op.add_column('projects', sa.Column('chunk_size', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('chunk_overlap', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('top_k', sa.Integer(), nullable=True))
    op.add_column('projects', sa.Column('deployment_environment', sa.String(), nullable=True))
    op.add_column('projects', sa.Column('is_public', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('role', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'role')
    op.drop_column('projects', 'is_public')
    op.drop_column('projects', 'deployment_environment')
    op.drop_column('projects', 'top_k')
    op.drop_column('projects', 'chunk_overlap')
    op.drop_column('projects', 'chunk_size')
    op.drop_column('projects', 'temperature')
    op.drop_column('projects', 'embedding_model')
    op.drop_column('projects', 'llm_model')
    # ### end Alembic commands ###
